### ISSUE TITLE
Add examples and basic documentation

### ISSUE THREAD

**Issue by clue** [graphp/graph#105]

**Comment by keevitaja** [comment]
Hello!

I did not want to create new topic...

Any chance someone could give me a snipped how to use this for finding the shortest path?

I have connected nodes and i need to find the shortst path from node a to node b.

**Comment by clue** [comment]
Hi @keevitaja!

See also the linked ticket https://github.com/graphp/algorithms/issues/7 which raises the same documentation issue for our existing algorithms :-)

I encourage you to take a closer look at the [graphp/algorithms package](https://github.com/graphp/algorithms), your best bet would probably be the test suite: https://github.com/graphp/algorithms/tree/master/tests/ShortestPath

Any suggestions and PRs(!) to improve this would be much appreciated! :+1:

**Comment by clue** [comment]
I'd like to make open issue actionable and it's unclear what needs to be changed for "example and basic documentation" to be completed. I've just closed this via #172, but more input will make sense in the future :+1:
