### ISSUE TITLE
We should add some more code style to travis

### ISSUE THREAD

**Issue by clemens-tolboom** [graphp/graph#107]
In #106 I noted a missing end of file newline.

Are there more CS test we should add?

**Comment by clue** [comment]
Ping @clemens-tolboom, what's the status on this ticket?

Admittedly, personally I'm not seeing an *immediate need* at this moment. However, given that Scrutinizer has a free plan for open source projects, I'm not opposed to giving it a try.

Any thoughts?

**Comment by clemens-tolboom** [comment]
Hi @clue I would say go for it (scrutinizer).

BTW I'm not very useful last year and prob next year. Feel free to kick me from the project(s).

**Comment by clue** [comment]
I'll assume this is resolved and will close this for now, please feel free to report back otherwise :+1:
