### ISSUE TITLE
Move to graphp organization

### ISSUE THREAD

**Issue by clue** [graphp/graph#130]
Now that all components have been split off into separate packages under the [graphp organization](https://github.com/graphp), we should eventually also move this repository.

Things to consider:
- Does this involve any BC breaks? What about consumers of this package?
- Should we rename this package to the "graphp" vendor?
- If so, what package name should we assign?

I'd like to migrate previous issues, PR, among with all watchers and stargazers, so forking does not seem to be an option.

Any input would be much appreciated!

**Comment by clemens-tolboom** [comment]
I recently __moved__ a repo then cloned it back on the __old__ location then removed all files except for the README.md to tell about the move.

Old consumers will still find the releases on the old location.

Do not forget to tell https://packagist.org

**Comment by clue** [comment]
Thanks for the feedback!

Moving this repository to the [graphp organization](https://github.com/graphp) should actually be a no-brainer, given that GitHub automatically sets up redirects and Composer does a reasonable good job at following redirects.

I'm voting for *moving* this repository instead of setting up a clone (in either direction) because this will set up a working redirect for *all* existing links (including issues/PRs etc.)

The future home will *likely* be [graphp/graph](https://github.com/graphp/graph), though I'm not entirely sure I like the name (could be confusing?). Perhaps an additional redirect from graphp/graphp to graphp/graph (notice the subtle trailing *p*) could help? Also keep in mind the name is not set in stone…

Any input is welcome!

FWIW, renaming the package will be the next step that will probably be postponed for a few weeks (just in case).

**Comment by clue** [comment]
Ping @all:

What do you think about the name "graphp/graph"?

Any better suggestions?

**Comment by clue** [comment]
> Ping @all:
> What do you think about the name "graphp/graph"?

:shipit: ?

**Comment by clemens-tolboom** [comment]
I like the organization name. And hopefully it would be a good starting point finding sponsors.

**Comment by clue** [comment]
For the reference, this ticket is only about *moving* this repo to the [graphp organization](https://github.com/graphp), without affecting the composer package name. As such, this should not have a huge impact on our existing user base.

Updating the package name will be postponed to #134, as this will break compatibility with all existing users.

> I like the organization name.

So do I :-) However, I'm not sure about the project name within this organization:

graphp/graph ?
graphp/graphp ?

This also affects the PHP namespace and class names:

```
Graphp\Graph\Graph ?
Graphp\Graph\Vertex
```

> And hopefully it would be a good starting point finding sponsors.

Not sure I follow… what do you have in mind? :-)

**Comment by clemens-tolboom** [comment]
Ic � what about graphp/core ?

**Comment by clue** [comment]
I like your suggestion, but then again, what is a "core"? :-)

https://en.wikipedia.org/wiki/Core_%28graph_theory%29

**Comment by clemens-tolboom** [comment]
core is core of graphp/* � guess kernel / base as similar disputable :p

**Comment by EmanueleMinotto** [comment]
> Does this involve any BC breaks? What about consumers of this package?

To prevent any BC, I would move everything from PSR-4 to PSR-0 (e.g. src/Exception.php to src/Fhaculty/Graph/Exception.php), move old sources under the new namespace, make them extend the old classes (empty classes used temporary only to maintain the original type) and use a [deprecations system](http://symfony.com/doc/current/contributing/code/conventions.html#contributing-code-conventions-deprecations) to allow users to adapt their sources.

Example:

```php
// src/Fhaculty/Graph/Graph.php

/**
 * @deprecated Deprecated since version 0.9, to be removed in 1.0. Use Graphp\Graph\Graph instead.
 */
class Graph
{
}

// src/Graphp/Graph/Graph.php

class Graph extends \Fhaculty\Graph\Graph
{
  // ...
}
```

Of course this change should be done in composer.json too, but that's considered an internal change, no APIs are involved.
The code shouldn't stay dirty for a long time considering that this library is at v0.9.

> Should we rename this package to the "graphp" vendor?
> If so, what package name should we assign?

Yes, I'm +1 for graphp/graph

Also the repository redirect is no more a pain.
If you need a help I'm available, https://github.com/graphp seems a really nice project. :)

**Comment by clue** [comment]
> Does this involve any BC breaks? What about consumers of this package?

Thanks for your valuable input @EmanueleMinotto, but I believe most of this actually belongs to #134 :+1: 

This ticket here is only concerned with moving the repository to the https://github.com/graphp GitHub organization. As far as I can tell, this does not involve any BC breaks whatsoever, now that GitHub will setup redirects for HTTP and git links and composer seems to be able to cope with this just as well.

>> Should we rename this package to the "graphp" vendor?
> Yes, I'm +1 for graphp/graph

Thanks! I think we agree here, so let's move forward on this one :+1:

**Comment by clemens-tolboom** [comment]
I found https://github.com/graphp/graph which confuses me. It is a clone of this repo https://github.com/clue/graph which contradicts https://github.com/clue/graph/issues/130#issuecomment-116861859 

> Moving this repository to the graphp organization should actually be a no-brainer, given that GitHub automatically sets up redirects and Composer does a reasonable good job at following redirects.

See also https://github.com/graphp/graph/network. I'm confused.

Regarding the name I'm still fine with graphp/graph :)
