### ISSUE TITLE
Return $this in Vertex::setAttribute 

### ISSUE THREAD

**Issue by Bogdaan** [graphp/graph#132]
How about return $this value in 
https://github.com/clue/graph/blob/master/src/Vertex.php#L380
(fluent interface) ?

**Comment by clue** [comment]
Thanks for the input!

`Vertex::setAttribute()` actually implements [`AttributeAware::setAttribute()`](https://github.com/clue/graph/blob/0336a4d5229fa61a20ccceaeab25e52ac9542700/src/Attribute/AttributeAware.php#L27) which is also used in several other places. This has been implemented as part of #103/#100.

So far, the return type has not been discussed at all and it not consistently defined as part of the interface. To add to this, multiple classes implementing this interface actually do return different values.

I think it makes sense to add a consistent definition anyway – and personally, I think it's a good fit for a fluent interface (though there are valid concerns with fluent interfaces).

@all: Any feedback would be much appreciated!

**Comment by dav-m85** [comment]
:+1: fluent spares typing. Feels normal to me that mutator return self instance. Would be less obvious for more complex function.

**Comment by jkuchar** [comment]
Don't you want to make composition which provides fluent interface? This breaks encapsulation - [more here](https://ocramius.github.io/blog/fluent-interfaces-are-evil/)

**Comment by clue** [comment]
@jkuchar I think this post includes valid concerns, however I'm undecided in this case here. Can you elaborate on why you think this is problematic?
