### ISSUE TITLE
Adding a loop to vertex produces two edges

### ISSUE THREAD

**Issue by lezhnev74** [graphp/graph#152]
Is it desired behavior? For me it was counter-intuitive. What do you think?

```php
echo $vertex->getEdgesOut()->count(); // will give us 0
echo $vertex->getEdgesIn()->count(); // will give us 0

$vertex->createEdgeTo($vertex);

echo $vertex->getEdgesOut()->count(); // will give us 2
echo $vertex->getEdgesIn()->count(); // will give us 2
```

**Comment by clue** [comment]
Yes, I understand this may seem counterintuitive, but this is actually desired behavior. :+1: 

This does make sense from a mathematical perspective, because a vertex with a loop edge is said to have a degree of 2 (i.e. two endpoints of edges reach it).

I hope this helps :+1:

**Comment by lezhnev74** [comment]
Cool, thanks for pointing this out.
In case I want to have only unique edges, I'd do this:

```php
echo $vertex->getEdgesOut()->getEdgesDistinct()->count(); // will give us 0
echo $vertex->getEdgesIn()->getEdgesDistinct()->count(); // will give us 0
    
$vertex->createEdgeTo($vertex);
    
echo $vertex->getEdgesOut()->getEdgesDistinct()->count(); // will give us 1
echo $vertex->getEdgesIn()->getEdgesDistinct()->count(); // will give us 1
```

**Comment by jacobalvarez** [comment]
> This does make sense from a mathematical perspective, because a vertex with a loop edge is said to have a degree of 2 (i.e. two endpoints of edges reach it).

That does make sense if the edge isn't directed. Shouldn't a directed edge only count once?

**Comment by clue** [comment]
> > This does make sense from a mathematical perspective, because a vertex with a loop edge is said to have a degree of 2 (i.e. two endpoints of edges reach it).
> 
> That does make sense if the edge isn't directed. Shouldn't a directed edge only count once?

For directed loop edges the same logic applies: The loop edge "points away" from vertex A and "points towards" vertex A, so it is included once in `getEdgesOut()` and once in `getEdgesIn()`.

**Comment by jacobalvarez** [comment]
Right, but the issue is it's being included twice for getEdgesOut().

**Comment by clue** [comment]
@jacobalvarez You're right, what you're describing is indeed a bug in this library, thank you for making us aware of it :+1: 

Directed loop edges will indeed be included twice in both `getEdgesIn()` and `getEdgesOut()` while they only be included once in each. All other edge combinations seem to work just fine. I'll take a look at this as soon as time permits :shipit:
