### ISSUE TITLE
Namespace Fhaculty\Graph after installed

### ISSUE THREAD

**Issue by r-augustine** [graphp/graph#190]
The current namespace after installed is Fhaculty\Graph\Graph and the methods "createEdgeDirected/createEdgeUndirected" are undefined

**Comment by clue** [comment]
Hi @r-augustine, welcome to this project :wave:

It looks like your referring to the documentation of the current `master` branch which will be released as `v1.0.0` not too far in the future – while you're watching the source code of the `v0.9.x` release branch.

Please refer to the documentation that comes with your installed version or wait for the `v1.0.0` release which will come with a much better architecture and documentation. In the meantime, you can also install from the `master` branch to get the latest development version :+1:
