### ISSUE TITLE
Releases needed

### ISSUE THREAD

**Issue by visitek** [graphp/graph#191]
We use this package with github commit reference because there are missing composer releases.

Please fix it.

**Comment by clue** [comment]
The current `master` branch which will be released as `v1.0.0` not too far in the future. In the meantime, you can continue using the `v0.9.x` release tags or keep using commit references if you want to use the latest version.

*(If you need this for a commercial project and if you want to help sponsor this development, feel free to reach out)*

Refs https://github.com/graphp/graph/issues/190
