### ISSUE TITLE
Consider to update your CHANGELOG

### ISSUE THREAD

**Issue by llaville** [graphp/graph#196]
Please consider to update your CHANGELOG even for commits/PR that are not yet published.

Following pseudo-standard https://keepachangelog.com/en/1.0.0/ and especially the `Unreleased` section.

That will allows to other project that use the `graphp/graph` master branch to upgrade it easily!

Main reason, is of course changes occured with : 
- https://github.com/graphp/graph/pull/193
- https://github.com/graphp/graph/pull/195

Thanks in advance

**Comment by clue** [comment]
The current `master` branch which will be released as `v1.0.0` not too far in the future. As usual, we will make sure to update the CHANGELOG.md when preparing the release.

In the meantime, you can continue using the `v0.9.x` release tags or keep using commit references if you're sure you want to use the latest beta version.

Refs #191, #190 and others
