### ISSUE TITLE
What is missing for release 1.0.0?

### ISSUE THREAD

**Issue by DanielBadura** [graphp/graph#197]
Hey 👋 

I wanted to ask what is missing  for the 1.0.0 release / what needs to be done before the release can be done.
In some issues you stated that the release will be done in the near future and im happy to hear that! :)

I just wanted to ask so maybe people can help out to get to the 1.0.0 release. At the moment no open issues for the milestone so it's difficult to get a foot into helping out. Or is everything finished and the release is just not done yet?

**Comment by clue** [comment]
@DanielBadura Thanks for bringing this up, very valid question indeed! :-)

Most of the planned changes for the upcoming release have been merged already! This is going to be a somewhat major release, see https://github.com/graphp/graph/milestone/7?closed=1 for the full list.

With all these BC breaks here, all components that depend on this core graph component also need to be updated. This means it requires a concentrated effort to update all other components in the @GraPHP organization as well.

If you feel like helping, you're more than welcome to check out all components and make sure they're compatible with the latest beta version from this repository. I'm super happy to accept PRs!

As much as I'd like to commit to specific date, I can only say that we will get to this as soon as time permits. If you need this for a commercial project and you want to help sponsor this release, feel free to reach out and I'm sure we can sort this out.

**Comment by clue** [comment]
I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can always reopen this :+1:
