### ISSUE TITLE
v0.9.3 Composer package name is 'clue/graph'

### ISSUE THREAD

**Issue by joachim-n** [graphp/graph#210]
composer.json on the 0.9.x branch still has:

```
    "name": "clue/graph",
```

**Comment by SimonFrings** [comment]
Hey @joachim-n, this is correct, the name of the project inside v0.9 is still `clue/graph`. The rename of the project to `graphp/graph` will come with the next version, which is the current development version.

 This topic has also been addressed in #201 and #134. There will be a new version when the time is given :+1:

**Comment by SimonFrings** [comment]
I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can always reopen this :+1:.
