### ISSUE TITLE
Trees support

### ISSUE THREAD

**Issue by Houssem-Guemer** [graphp/graph#216]
Are there any plans to implement tree structures ? 

I would love to work on that and add it to this library since trees are an essential part of graph theory.

**Comment by yadaiio** [comment]
Hey @[Houssem-Guemer](https://github.com/Houssem-Guemer), thanks for bringing this up! 

I had the same question and talked with @clue about this. I also started a research for the graph theory and it looks like it is a complex topic and there are many different approaches how we could create graphs, apart from all the edge cases that still exist. 

Considering the depth and complexity of this topic, it might be worth developing it as a standalone repository, as we are not sure if we should implement each individual tree algorithm into this project. 

I think this should answer your question, so I'll close this for now. As I said above, I think the whole tree topic should be a project of its own and not part of this repository. This means we will probably don't merge any PRs here, but you can always fork this project and add the needed functionality.

Hope this helps 👍️
